### ISSUE TITLE
Pyoctree Attribute Error

### ISSUE THREAD

**Issue by lucarei** [AndrejOrsula/drl_grasping#103]
Hi Andrej. Thanks for your work and for a previous answer. I am trying to make a local installation (yet tried Docker, it works perfectly but i need much more personalization; for example i want to use the UR5 and a modified environment).
I installed all the needed dependancies following the instructions found in Dockerfile (even colcon command seems to finish correctly).

However, when i run an example (like "ros2 run drl_grasping ex_random_agent.bash") RVIZ gives me the following warning "severe warning for a namespace collision" and Gazebo is not opened: i think that this warning is not a problem since it appears also when i use Docker.

The main error is related to pyoctree -> "Attribute Error: module 'pyoctree' has no attribute 'Points'.

![image](https://user-images.githubusercontent.com/128145979/227966679-2fa536a9-acfb-424b-b02e-d1a47d7e3792.png)
![image](https://user-images.githubusercontent.com/128145979/227969278-09625756-4e72-4fcf-9de1-0597470954cb.png)

PS: are all the commands from the Dockerfile enough to install correctly or can you share with me other tips?

**Comment by lucarei** [comment]
Issue solved using “export PYTHONPATH=~/ws/src/OCNN/octree/build/python:${PYTHONPATH}

**Comment by AndrejOrsula** [comment]
Glad you were able to resolve it!

> PS: are all the commands from the Dockerfile enough to install correctly or can you share with me other tips?

The Dockerfile "was" enough to install everything correctly. However, the versions of dependencies for some ROS packages and all Gazebo libraries are not fixed (these dependencies are installed as Debian packages that do not archive past releases, so it is not possible to fix them). Therefore, if these introduce any breaking changes (ideally, this should not occur) - the Dockerfile might not be valid anymore, and some issues might appear (e.g. compile-time errors, run-time errors or change in computational/learning performance). ROS 2 `galactic` is now EOL, so it won't be getting updates - which means that these dependencies *should* be fine. However, updates to `fortress` could possibly introduce changes that affect this repository.
