### ISSUE TITLE
Deploying on Franka Research 3 (real)

### ISSUE THREAD

**Issue by lif314** [AndrejOrsula/drl_grasping#111]
Could you please provide a code example for deploying on FR3 using ROS2? Thank you!

**Comment by AndrejOrsula** [comment]
Hello,

You can find a general example for evaluating models on real robots under [examples/ex_evaluate_real.bash](https://github.com/AndrejOrsula/drl_grasping/blob/b2283544d19c3b202b14caa03e233ac4598ccee2/examples/ex_evaluate_real.bash). It contains the information about relevant parts that need to be running alongside their configuration.

However, there is no example of using Franka Research 3 specifically. I don't have access to such robot.
You would need to add support for this robot yourself (e.g. in your own fork).

**Comment by lif314** [comment]
> Hello,
> 
> You can find a general example for evaluating models on real robots under [examples/ex_evaluate_real.bash](https://github.com/AndrejOrsula/drl_grasping/blob/b2283544d19c3b202b14caa03e233ac4598ccee2/examples/ex_evaluate_real.bash). It contains the information about relevant parts that need to be running alongside their configuration.
> 
> However, there is no example of using Franka Research 3 specifically. I don't have access to such robot. You would need to add support for this robot yourself (e.g. in your own fork).

Thanks for your prompt reply!
